### ISSUE TITLE
Sometime file will be lost something(share formula?)after modified by qxlsx

### ISSUE THREAD

**Issue by liufeijin** [QtExcel/QXlsx#32]
but can repaired by office and seems anything is ok.
https://github.com/liufeijin/QXlsx/blob/master/TestExcel/C1804093.xlsx
this is the file with problem.

https://app.leanboard.io/board/9a33da08-9352-4a63-942f-b99803e98324

**Comment by j2doll** [comment]
Thank you for reporting this issue.

Here are the test results:
- The file does not open in Microsoft Excel (online).
- But, It will open normally in Google Spreadsheets.

Can I see the code that generated the Excel file?

**Comment by liufeijin** [comment]
QXlsx::Document xlsx(excelFileName);
    if (!xlsx.isLoadPackage())
    {
         QMessageBox::information(this,tr("read data"),excelFileName+tr("can't open the file！"));
     }else{
      
         if(xlsx.selectSheet("sheet1")){

               TankTotalNum=0;
               VesselNC="";
               VesselNE="";
               CertNo="";
               CertNo=xlsx.read(3,2).toString().trimmed();
               VesselNC=xlsx.read(4,2).toString().trimmed();
               VesselNE=xlsx.read(5,2).toString().trimmed();
         }
          ............


    if(xlsx.selectSheet("sheet1")){
           for (int i=0;i<TankTotalNum;++i){
               xlsx.write(i+3,18,EndHeight[i]);
               xlsx.write(i+3,19,MarkHeight[i]);
             }
            xlsx.write(2,18,tr("incline ending"));
            xlsx.write(2,19,tr("incline marking"));
     }
    xlsx.save();

}
Seems after written some thing hidden in the excel is lose. (use office open it give tips is shared formula losing . if accept excel to repair , the file can be open.
Seems  it is ok if the original excel doesn't include something(shared formula).

**Comment by liufeijin** [comment]
PLS download it
https://github.com/liufeijin/QXlsx/blob/master/TestExcel/C1804093.rar

**Comment by j2doll** [comment]
I have found the following:
 - The file [C1804093.rar](https://github.com/liufeijin/QXlsx/blob/master/TestExcel/C1804093.rar) is not a zip-compressed file. It is a html format file.
 
![hxd-cap](https://user-images.githubusercontent.com/1289306/51878869-94db5b80-23b4-11e9-84c8-a45601f3e688.png)

**Comment by liufeijin** [comment]
hi j2doll
I don't know why it is wrong the rar file you download.
Anyway , i sent it to you via your gmail.

Kindly  PLS check your email.
best regards,
jeff

**Comment by j2doll** [comment]
I wrote the test code in new branch '**shared-formula**'.
https://github.com/QtExcel/QXlsx/tree/shared-formula

Try the test, and tell me the result. (Don't use master branch.)

**Comment by liufeijin** [comment]
hi J2doll
Many thanks for your response.
I use your Shared-formula branch to test , but it is still same error.

**Comment by liufeijin** [comment]
I send you a rar via email that contains the original excel and afterwritten excel file.
compare 1 same sheet maybe you can find something.
Best regards,
jeff

**Comment by j2doll** [comment]
Try the test, and tell me the result. (test branch is shared-formula)

Now, the following attributes are not implemented:
- aca (Always Calculate Array)
- bx (Assigns Value to Name) 
- del1 (Input 1 Deleted) 
- del2 (Input 2 Deleted) 
- dt2D (Data Table 2-D)
- dtr (Data Table Row) 
- r1 (Data Table Cell 1)
- r2 (Input Cell 2)

**Comment by liufeijin** [comment]
Hi j2doll
You can just open the original excel file and write any value to any cell (just 1 enough).
And then open the written excel file , office will give the tips that something wrong the shared formula to be deleted for continue opening . 
So i think something(about shared formula) is no written back or written wrong ,so when open it by office the unreasonable (or wrong) formula to be deleted for continue opening.

**Comment by j2doll** [comment]
Well, I think more testing and complementary work is required. 

Thank you for reporting.

I will keep this issue.

**Comment by j2doll** [comment]
Hi.
I fixed some code for testing.
If possible, try to test it.

- Test branch is 'dev34'. https://github.com/QtExcel/QXlsx/tree/dev34
- Use 'git checkout dev34'

**Comment by rickbase1** [comment]
Hi Jay Two,

Thanks for the effort.  By chance is there a way to create chart legends
yet?

Thanks

Rick

**Comment by j2doll** [comment]
Dear @rickbase1 

I think it will take more time to analyze the function. :sob:

I'll check that issue in #31

**Comment by rickbase1** [comment]
Great!

Thanks very much !!!

Rick

**Comment by liufeijin** [comment]
> Hi.
> I fixed some code for testing.
> If possible, try to test it.
> 
> * Test branch is 'dev34'. https://github.com/QtExcel/QXlsx/tree/dev34
> * Use 'git checkout dev34'

Dear j2doll
Many thanks for your work!
But the error is still present.
<removedRecord>已删除的记录: /xl/worksheets/sheet4.xml 部分的 共享公式</removedRecord>
<removedRecord>已删除的记录: /xl/worksheets/sheet5.xml 部分的 共享公式</removedRecord>
<removedRecord>已删除的记录: /xl/worksheets/sheet6.xml 部分的 共享公式</removedRecord>
<removedRecord>已删除的记录: /xl/worksheets/sheet7.xml 部分的 共享公式</removedRecord>
<removedRecord>已删除的记录: /xl/worksheets/sheet10.xml 部分的 共享公式</removedRecord>
<removedRecord>已删除的记录: /xl/worksheets/sheet11.xml 部分的 共享公式</removedRecord>
<removedRecord>已删除的记录: /xl/worksheets/sheet12.xml 部分的 共享公式</removedRecord>
<removedRecord>已删除的记录: /xl/worksheets/sheet13.xml 部分的 共享公式</removedRecord>
<removedRecord>已删除的记录: /xl/worksheets/sheet14.xml 部分的 共享公式</removedRecord>
<removedRecord>已删除的记录: /xl/worksheets/sheet18.xml 部分的 共享公式</removedRecord>
<removedRecord>已删除的记录: /xl/worksheets/sheet19.xml 部分的 共享公式</removedRecord>
<removedRecord>已删除的记录: /xl/worksheets/sheet20.xml 部分的 共享公式</removedRecord>
<removedRecord>已删除的记录: /xl/worksheets/sheet21.xml 部分的 共享公式</removedRecord>
<removedRecord>已删除的记录: /xl/worksheets/sheet22.xml 部分的 共享公式</removedRecord>
<removedRecord>已删除的记录: /xl/worksheets/sheet23.xml 部分的 共享公式</removedRecord>
I think i have no time to find where is the problem in QXlsx till Sep this year(need pay attention on a hurry project).
Thanks again for your hard work on this!
Jeff

**Comment by liufeijin** [comment]
> Hi.
> I fixed some code for testing.
> If possible, try to test it.
> 
> * Test branch is 'dev34'. https://github.com/QtExcel/QXlsx/tree/dev34
> * Use 'git checkout dev34'

Hi 
I delete other items and found what status the error will be present.
The two rows present together ,after write data to excel file , the error will present when open file by office
Delete any row , after write data to excel file , no error present when open file by office
![2](https://user-images.githubusercontent.com/19425403/52714606-42658600-2fd5-11e9-99e1-5014a94237ae.png)

I change the file testorignal.xlsx ,testbadafterwrite.xlsx to testorignal.zip ,testabadafterwrite.zip and get the sheet1.xml  ,compare it, found, some part will be lose when file write data to excel file.
![2](https://user-images.githubusercontent.com/19425403/52714775-bbfd7400-2fd5-11e9-9747-bffee8bddcab.png)


i warp all file in desktop.zip 
[Desktop.zip](https://github.com/QtExcel/QXlsx/files/2860496/Desktop.zip)

for your reference.

**Comment by j2doll** [comment]
Dear @liufeijin 

I think I know roughly what happened.

- Cell 'J1' of file 'testoriginal.xlsx' is **boolean type(b)**, it is not number type.
- Only **number type** of cell can handle **formula**.

This conclusion is based on the ECMA 376 standard.
- Cell type(t) can be 'Boolean', 'Date', 'Error', 'Inline String', 'Number', 'Shared String', 'String'. and it is based on W3C XML Scema string datatype. 

I do not know how the file was created, but I think if I knew exactly how to do it, I would be able to do a more accurate analysis. :sunglasses:

**Comment by liufeijin** [comment]
The problem is if only has 1 row  , it will be not error 。 
I checked again  the 'J1' present FALSE as when "A1"..."B1".....Cell has data and office does a data verification 
![1](https://user-images.githubusercontent.com/19425403/52782125-45ba4980-3089-11e9-9610-2efee802f6e2.png)
![Uploading T1.png…]()


I have no English office, so i take a picture to show the button .
![t1](https://user-images.githubusercontent.com/19425403/52781881-9e3d1700-3088-11e9-991e-84b9da1bb44f.png)

**Comment by j2doll** [comment]
I modified the processing of 'boolean type cell' again. 

Try the test.

- test branch is [dev34](https://github.com/QtExcel/QXlsx/tree/dev34)

**Comment by liufeijin** [comment]
Oh...
Great!
You fix it prefect!
Now it works fine!
Many thanks for your great work!

Best regards,
jeff

**Comment by j2doll** [comment]
I'll close this issue.

**Comment by liufeijin** [comment]
OK.
Thanks again.
